# Generated by Django 5.2.7 on 2026-07-23 03:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limnigrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('memoria', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tipo_de_comunicacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('internet-https-2G', 'Internet HTTPS 2G'), ('internet-https-3G', 'Internet HTTPS 3G'), ('internet-https-4G', 'Internet HTTPS 4G'), ('internet-https-5G', 'Internet HTTPS 5G'), ('fisico-usb', 'Físico USB'), ('mensajes-sms', 'Mensajes SMS'), ('correos-smtp', 'Correos SMTP')], max_length=25), default=list, size=None)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('bateria_actual', models.FloatField(blank=True, null=True)),
                ('radio_cobertura_metros', models.PositiveIntegerField(blank=True, null=True)),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('advertencia', 'Advertencia'), ('peligro', 'Peligro'), ('sin_conexion', 'Sin conexión')], default='normal', max_length=20)),
                ('estado_medicion', models.CharField(choices=[('normal', 'Normal'), ('fuera_de_rango', 'Fuera de rango')], default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('legajo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('created', 'Creación'), ('modified', 'Modificación'), ('deleted', 'Eliminación'), ('manual_data_load', 'Carga manual de datos'), ('import_data_load', 'Importación de datos')], db_index=True, default='modified', max_length=32)),
                ('entidad', models.CharField(db_index=True, default='', max_length=80)),
                ('entidad_id', models.CharField(blank=True, default='', max_length=64)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('review', 'En revisión')], default='success', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionLimnigrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_advertencia', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tiempo_peligro', models.PositiveBigIntegerField(blank=True, null=True)),
                ('bateria_min', models.FloatField(blank=True, null=True)),
                ('bateria_max', models.FloatField(blank=True, null=True)),
                ('altura_minima_agua', models.FloatField(blank=True, null=True)),
                ('altura_maxima_agua', models.FloatField(blank=True, null=True)),
                ('temperatura_minima', models.FloatField(default=0)),
                ('temperatura_maxima', models.FloatField(default=100)),
                ('presion_minima', models.FloatField(blank=True, null=True)),
                ('presion_maxima', models.FloatField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('limnigrafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='api.limnigrafo')),
            ],
            options={
                'verbose_name': 'Configuración de Limnígrafo',
                'verbose_name_plural': 'Configuraciones de Limnígrafos',
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('altura_agua', models.FloatField()),
                ('presion', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('nivel_de_bateria', models.FloatField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('fuente', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('import_csv', 'Importación CSV'), ('import_json', 'Importación JSON')], default='automatico', max_length=20)),
                ('limnigrafo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='api.limnigrafo')),
            ],
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='ultima_medicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.medicion'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('leido', 'Leído'), ('solucionado', 'Solucionado')], default='nuevo', max_length=20)),
                ('tipo', models.CharField(choices=[('fuera_rango_medicion', 'Por fuera de rango de medición'), ('advertencia_limnigrafo', 'Por advertencia de limnígrafo'), ('peligro_limnigrafo', 'Por peligro de limnígrafo'), ('sin_conexion_limnigrafo', 'Por falta de conexión del limnígrafo')], max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('usuarios', models.ManyToManyField(related_name='alertas', to=settings.AUTH_USER_MODEL)),
                ('limnigrafo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='api.limnigrafo')),
                ('medicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='api.medicion')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('intentos', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuarios', models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RutaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('tiempo_estimado_minutos', models.FloatField(null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('track', models.TextField(blank=True, null=True)),
                ('formato_origen', models.CharField(blank=True, choices=[('gpx', 'GPX'), ('kml', 'KML')], max_length=3)),
                ('archivo_original', models.FileField(blank=True, null=True, upload_to='rutas_acceso/')),
                ('geometria', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('limnigrafo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas_acceso', to='api.limnigrafo')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_acceso', to='api.ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='limnigrafo', to='api.ubicacion'),
        ),
        migrations.CreateModel(
            name='HistoricalLimnigrafo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('memoria', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tipo_de_comunicacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('internet-https-2G', 'Internet HTTPS 2G'), ('internet-https-3G', 'Internet HTTPS 3G'), ('internet-https-4G', 'Internet HTTPS 4G'), ('internet-https-5G', 'Internet HTTPS 5G'), ('fisico-usb', 'Físico USB'), ('mensajes-sms', 'Mensajes SMS'), ('correos-smtp', 'Correos SMTP')], max_length=25), default=list, size=None)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('bateria_actual', models.FloatField(blank=True, null=True)),
                ('radio_cobertura_metros', models.PositiveIntegerField(blank=True, null=True)),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('advertencia', 'Advertencia'), ('peligro', 'Peligro'), ('sin_conexion', 'Sin conexión')], default='normal', max_length=20)),
                ('estado_medicion', models.CharField(choices=[('normal', 'Normal'), ('fuera_de_rango', 'Fuera de rango')], default='normal', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ultima_medicion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.medicion')),
                ('ubicacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.ubicacion')),
            ],
            options={
                'verbose_name': 'historical limnigrafo',
                'verbose_name_plural': 'historical limnigrafos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UsuarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('leido', 'Leído'), ('solucionado', 'Solucionado')], default='nuevo', max_length=20)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_usuario', to='api.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='medicion',
            constraint=models.UniqueConstraint(fields=('limnigrafo', 'fecha_hora'), name='uniq_medicion_limnigrafo_fecha_hora'),
        ),
        migrations.AddConstraint(
            model_name='medicion',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('limnigrafo', 'idempotency_key'), name='uniq_medicion_limnigrafo_idempotency_key'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarionotificacion',
            unique_together={('usuario', 'alerta')},
        ),
    ]
