# Generated by Django 5.2.7 on 2025-11-22 15:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limnigrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('memoria', models.PositiveIntegerField()),
                ('tipo_de_comunicacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('internet-https-2G', 'Internet HTTPS 2G'), ('internet-https-3G', 'Internet HTTPS 3G'), ('internet-https-4G', 'Internet HTTPS 4G'), ('internet-https-5G', 'Internet HTTPS 5G'), ('fisico-usb', 'Físico USB'), ('mensajes-sms', 'Mensajes SMS'), ('correos-smtp', 'Correos SMTP')], max_length=25), default=list, size=None)),
                ('bateria_max', models.FloatField()),
                ('bateria_min', models.FloatField()),
                ('tiempo_de_advertencia', models.TimeField()),
                ('tiempo_de_peligro', models.TimeField()),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('advertencia', 'Advertencia'), ('peligro', 'Peligro'), ('fuera_de_servicio', 'Fuera de servicio')], default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SectorRio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rio', models.CharField(max_length=100)),
                ('nombre_sector', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cuenca', models.CharField(max_length=100)),
                ('geometria', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('altitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('altura', models.FloatField()),
                ('presion', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('nivel_de_bateria', models.FloatField()),
                ('limnigrafo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='api.limnigrafo')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('leido', 'Leído'), ('solucionado', 'Solucionado')], default='nuevo', max_length=20)),
                ('tipo', models.CharField(choices=[('fuera_rango_medicion', 'Por fuera de rango de medición'), ('advertencia_limnigrafo', 'Por advertencia de limnígrafo'), ('peligro_limnigrafo', 'Por peligro de limnígrafo')], max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('usuarios', models.ManyToManyField(related_name='alertas', to=settings.AUTH_USER_MODEL)),
                ('limnigrafo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='api.limnigrafo')),
                ('medicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='api.medicion')),
            ],
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='sector_rio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limnigrafos', to='api.sectorrio'),
        ),
        migrations.CreateModel(
            name='RutaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('distancia_km', models.FloatField()),
                ('tiempo_estimado_minutos', models.FloatField(null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('track', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_acceso', to='api.ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='ubicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='limnigrafo', to='api.ubicacion'),
        ),
    ]
