# Generated by Django 5.2.7 on 2025-11-22 22:10

import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_limnigrafo_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limnigrafo',
            old_name='tiempo_de_advertencia',
            new_name='tiempo_advertencia',
        ),
        migrations.RenameField(
            model_name='limnigrafo',
            old_name='tiempo_de_peligro',
            new_name='tiempo_peligro',
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='bateria_actual',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='ultima_conexion',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='HistoricalLimnigrafo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('memoria', models.PositiveIntegerField()),
                ('tipo_de_comunicacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('internet-https-2G', 'Internet HTTPS 2G'), ('internet-https-3G', 'Internet HTTPS 3G'), ('internet-https-4G', 'Internet HTTPS 4G'), ('internet-https-5G', 'Internet HTTPS 5G'), ('fisico-usb', 'Físico USB'), ('mensajes-sms', 'Mensajes SMS'), ('correos-smtp', 'Correos SMTP')], max_length=25), default=list, size=None)),
                ('bateria_max', models.FloatField()),
                ('bateria_min', models.FloatField()),
                ('bateria_actual', models.FloatField(null=True)),
                ('ultima_conexion', models.TimeField(null=True)),
                ('tiempo_advertencia', models.TimeField()),
                ('tiempo_peligro', models.TimeField()),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('advertencia', 'Advertencia'), ('peligro', 'Peligro'), ('fuera_de_servicio', 'Fuera de servicio')], default='normal', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sector_rio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.sectorrio')),
                ('ubicacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.ubicacion')),
            ],
            options={
                'verbose_name': 'historical limnigrafo',
                'verbose_name_plural': 'historical limnigrafos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
