# Generated by Django 5.2.7 on 2025-11-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_tiempo_de_advertencia_limnigrafo_tiempo_advertencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallimnigrafo',
            name='ultimo_mantenimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='ultimo_mantenimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='fuente',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='automatico', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='nivel_de_bateria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='presion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
