# Generated by Django 5.2.7 on 2025-11-29 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historicallimnigrafo_ultimo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limnigrafo',
            name='sector_rio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='limnigrafos', to='api.sectorrio'),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='limnigrafo', to='api.ubicacion'),
        ),
    ]
