# Generated by Django 5.2.7 on 2025-12-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_limnigrafo_sector_rio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='altitud',
        ),
    ]
