# Generated by Django 5.2.7 on 2025-12-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_ubicacion_altitud'),
    ]

    operations = [
        # Primero eliminamos el campo (se perderán los datos de hora)
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='ultima_conexion',
        ),
        migrations.RemoveField(
            model_name='limnigrafo',
            name='ultima_conexion',
        ),
        # Luego lo recreamos como DateTimeField
        migrations.AddField(
            model_name='historicallimnigrafo',
            name='ultima_conexion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='ultima_conexion',
            field=models.DateTimeField(null=True),
        ),
    ]
