# Generated by Django 5.2.7 on 2025-12-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_historicallimnigrafo_ultima_conexion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicion',
            old_name='altura',
            new_name='altura_agua',
        ),
    ]
