# Generated by Django 5.2.7 on 2026-01-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_altura_medicion_altura_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
