# Generated by Django 5.2.7 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_ubicacion_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="legajo",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
