# Generated by Django 5.2.7 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_usuario_legajo"),
    ]

    operations = [
        migrations.AddField(
            model_name="accion",
            name="entidad",
            field=models.CharField(db_index=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="accion",
            name="entidad_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="accion",
            name="estado",
            field=models.CharField(
                choices=[("success", "Exitoso"), ("failed", "Fallido"), ("review", "En revisión")],
                default="success",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="accion",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="accion",
            name="tipo_accion",
            field=models.CharField(
                choices=[
                    ("created", "Creación"),
                    ("modified", "Modificación"),
                    ("deleted", "Eliminación"),
                    ("manual_data_load", "Carga manual de datos"),
                ],
                db_index=True,
                default="modified",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="accion",
            name="fecha_hora",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
