# Generated by Django 5.2.7 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_accion_auditoria_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accion",
            name="descripcion",
            field=models.TextField(),
        ),
    ]
