# Generated by Django 5.2.7 on 2026-03-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_accion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='legajo',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
