# Generated by Codex on 2026-03-11

from django.db import migrations, models
import django.db.models.deletion


def migrar_alertas_a_usuario_notificacion(apps, schema_editor):
    Alerta = apps.get_model("api", "Alerta")
    UsuarioNotificacion = apps.get_model("api", "UsuarioNotificacion")

    for alerta in Alerta.objects.prefetch_related("usuarios").all():
        for usuario in alerta.usuarios.all():
            UsuarioNotificacion.objects.get_or_create(
                usuario=usuario,
                alerta=alerta,
                defaults={"estado": alerta.estado},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_usuario_legajo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioNotificacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("estado", models.CharField(choices=[("nuevo", "Nuevo"), ("leido", "Leído"), ("solucionado", "Solucionado")], default="nuevo", max_length=20)),
                ("fecha_leida", models.DateTimeField(blank=True, null=True)),
                ("alerta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notificaciones_usuario", to="api.alerta")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notificaciones", to="api.usuario")),
            ],
            options={
                "unique_together": {("usuario", "alerta")},
            },
        ),
        migrations.RunPython(migrar_alertas_a_usuario_notificacion, migrations.RunPython.noop),
    ]
