# Generated by Django 5.2.7 on 2026-03-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rol_delete_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='legajo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
