# Generated by Django 5.2.7 on 2026-03-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_usuario_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='legajo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
