# Generated by Django 5.2.7 on 2026-03-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_usuario_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='bateria_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='bateria_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='memoria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='tiempo_advertencia',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='tiempo_peligro',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='bateria_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='bateria_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='memoria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='tiempo_advertencia',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='tiempo_peligro',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
