# Generated by Django 5.2.7 on 2026-03-18 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_historicallimnigrafo_bateria_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='bateria_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='bateria_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UsuarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('leido', 'Leído'), ('solucionado', 'Solucionado')], default='nuevo', max_length=20)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_usuario', to='api.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'alerta')},
            },
        ),
    ]
