# Generated by Django 5.2.7 on 2026-03-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_historicallimnigrafo_bateria_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='memoria',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='tiempo_advertencia',
        ),
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='tiempo_peligro',
        ),
        migrations.AddField(
            model_name='historicallimnigrafo',
            name='tiempo_advertencia',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallimnigrafo',
            name='tiempo_peligro',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limnigrafo',
            name='memoria',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='limnigrafo',
            name='tiempo_advertencia',
        ),
        migrations.RemoveField(
            model_name='limnigrafo',
            name='tiempo_peligro',
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='tiempo_advertencia',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='tiempo_peligro',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
