# Generated by Django 5.2.7 on 2026-03-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_historicallimnigrafo_memoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicion",
            name="fuente",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("automatico", "Automático"),
                    ("import_csv", "Importación CSV"),
                    ("import_json", "Importación JSON"),
                ],
                default="automatico",
                max_length=20,
            ),
        ),
    ]
