# Generated by Django 5.2.7 on 2026-03-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_historicallimnigrafo_memoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='tiempo_advertencia',
        ),
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='tiempo_peligro',
        ),
        migrations.RemoveField(
            model_name='limnigrafo',
            name='tiempo_advertencia',
        ),
        migrations.RemoveField(
            model_name='limnigrafo',
            name='tiempo_peligro',
        ),
    ]
