# Generated by Django 5.2.7 on 2026-03-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_historicallimnigrafo_tiempo_advertencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallimnigrafo',
            name='tiempo_advertencia',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallimnigrafo',
            name='tiempo_peligro',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='tiempo_advertencia',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limnigrafo',
            name='tiempo_peligro',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
