# Generated by Django 5.2.7 on 2026-05-29 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_accion_metrica_to_medicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='bateria_max',
        ),
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='bateria_min',
        ),
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='tiempo_advertencia',
        ),
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='tiempo_peligro',
        ),
        migrations.RemoveField(
            model_name='limnigrafo',
            name='bateria_max',
        ),
        migrations.RemoveField(
            model_name='limnigrafo',
            name='bateria_min',
        ),
        migrations.RemoveField(
            model_name='limnigrafo',
            name='tiempo_advertencia',
        ),
        migrations.RemoveField(
            model_name='limnigrafo',
            name='tiempo_peligro',
        ),
        migrations.CreateModel(
            name='ConfiguracionLimnigrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_advertencia', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tiempo_peligro', models.PositiveBigIntegerField(blank=True, null=True)),
                ('bateria_max', models.FloatField(blank=True, null=True)),
                ('bateria_min', models.FloatField(blank=True, null=True)),
                ('altura_minima_agua', models.FloatField(blank=True, null=True)),
                ('altura_maxima_agua', models.FloatField(blank=True, null=True)),
                ('temperatura_minima', models.FloatField(default=0)),
                ('temperatura_maxima', models.FloatField(default=100)),
                ('presion_minima', models.FloatField(blank=True, null=True)),
                ('presion_maxima', models.FloatField(blank=True, null=True)),
                ('limnigrafo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='api.limnigrafo')),
            ],
            options={
                'verbose_name': 'Configuración de Limnígrafo',
                'verbose_name_plural': 'Configuraciones de Limnígrafos',
            },
        ),
    ]
