# Generated by Django 5.2.7 on 2026-05-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_historicallimnigrafo_bateria_max_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS api_rutaacceso_track_9b3f1fea_id;',
            reverse_sql='CREATE INDEX IF NOT EXISTS api_rutaacceso_track_9b3f1fea_id ON api_rutaacceso USING gist (track);',
        ),
        migrations.AlterField(
            model_name='rutaacceso',
            name='track',
            field=models.TextField(blank=True, null=True),
        ),
    ]
