# Generated by Django 5.2.7 on 2026-05-29 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_rutaacceso_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limnigrafo',
            name='sector_rio',
        ),
        migrations.RemoveField(
            model_name='historicallimnigrafo',
            name='sector_rio',
        ),
        migrations.DeleteModel(
            name='SectorRio',
        ),
    ]
