# Generated by Django 5.2.7 on 2026-07-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_limnigrafo_sector_rio_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicion',
            constraint=models.UniqueConstraint(fields=('limnigrafo', 'fecha_hora'), name='unique_limnigrafo_fecha_hora'),
        ),
    ]
