# Generated by Django 5.2.7 on 2026-07-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_update_limnigrafo_estado_and_alerta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallimnigrafo',
            name='estado',
            field=models.CharField(choices=[('normal', 'Normal'), ('advertencia', 'Advertencia'), ('peligro', 'Peligro'), ('fuera_de_rango', 'Fuera de rango')], default='normal', max_length=20),
        ),
    ]
