# Generated by Django 5.2.7 on 2026-07-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rutaacceso_track_text_no_postgis'),
        ('api', '0031_limnigrafo_radio_cobertura_metros'),
    ]

    operations = [
    ]
