# Generated by Django 5.2.7 on 2026-07-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_merge_20260717_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='tipo_accion',
            field=models.CharField(choices=[('created', 'Creación'), ('modified', 'Modificación'), ('deleted', 'Eliminación'), ('manual_data_load', 'Carga manual de datos'), ('import_data_load', 'Importación de datos')], db_index=True, default='modified', max_length=32),
        ),
    ]
