# Generated by Codex on 2026-07-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_accion_tipo_accion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutaacceso',
            name='tipo_acceso',
        ),
    ]
