services:
  # Servicio de la Aplicación Django
  root_empty:
    image: nginx:alpine
    command: >
      sh -c 'printf "server { listen 80; location / { return 404; } }" > /etc/nginx/conf.d/default.conf
      && nginx -g "daemon off;"'
    labels:
      - traefik.enable=true
      - traefik.http.routers.root.rule=Host(`scarh.online`) && Path(`/`)
      - traefik.http.routers.root.entrypoints=websecure
      - traefik.http.routers.root.tls.certresolver=letsencrypt
      - traefik.http.services.root.loadbalancer.server.port=80
      - traefik.docker.network=red_prueba
    networks:
      - red_prueba
  web:
    image: felixop/scarh:latest
    container_name: scarh_api
    command: >
      sh -c "python manage.py migrate &&
       python manage.py runserver 0.0.0.0:8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.scarh.rule=Host(`api.scarh.online`)
      - traefik.http.routers.scarh.entrypoints=websecure
      - traefik.http.routers.scarh.tls.certresolver=letsencrypt
      - traefik.http.services.scarh.loadbalancer.server.port=8000
      - traefik.docker.network=red_prueba
    networks:
      - red_prueba
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_FIRST_NAME=${ADMIN_FIRST_NAME}
      - ADMIN_LAST_NAME=${ADMIN_LAST_NAME}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_IS_STAFF=${ADMIN_IS_STAFF}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - ACCESS_TOKEN_LIFETIME_MINUTES=${ACCESS_TOKEN_LIFETIME_MINUTES}
      - REFRESH_TOKEN_LIFETIME_DAYS=${REFRESH_TOKEN_LIFETIME_DAYS}
  next_app:
    image: felixop/scarh-frontend:latest
    container_name: scarh_web
    labels:
      - traefik.enable=true
      - traefik.http.routers.next.rule=Host(`scarh.online`)
      - traefik.http.routers.next.entrypoints=websecure
      - traefik.http.routers.next.tls.certresolver=letsencrypt
      - traefik.http.services.next.loadbalancer.server.port=3000
      - traefik.docker.network=red_prueba
    networks:
      - red_prueba
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
      - AUTH_SECRET=${AUTH_SECRET}
    

networks:
  red_prueba:
    external: true