FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY api/requirements.txt /app/
RUN pip install -r requirements.txt

COPY api /app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]