backend_url: http://localhost:8000
interval_minutes_min: 2
interval_minutes_max: 3
limnigrafos:
    - id: 1
      token: u987jMI2.xTpmc6npU5haCRqM5m72W6kMMINZfnZw
      altura_min: 0.5
      altura_max: 3.5
      temperatura_min: -5
      temperatura_max: 25
      presion_min: 950
      presion_max: 1050
      bateria_max: 100
      bateria_min: 10
      probabilidad_falla: 0.012
      duracion_falla_min: 15
      duracion_falla_max: 60
    - id: 2
      token: 4SkGCM9m.yHfP57MJL1fOm7a9ueKf3Mz2x4OIP6Oh
      altura_min: 0.5
      altura_max: 3.5
      temperatura_min: -5
      temperatura_max: 25
      presion_min: 950
      presion_max: 1050
      bateria_max: 100
      bateria_min: 10
      probabilidad_falla: 0.006
      duracion_falla_min: 8
      duracion_falla_max: 25
    - id: 3
      token: yEy0avni.WEmxudrMpIP2KbFGmWhxGKP8wIn3KeQl
      altura_min: 0.5
      altura_max: 3.5
      temperatura_min: -5
      temperatura_max: 25
      presion_min: 950
      presion_max: 1050
      bateria_max: 100
      bateria_min: 10
      interval_minutes_min: 0.35
      interval_minutes_max: 0.6
      probabilidad_falla: 0.003
      duracion_falla_min: 20
      duracion_falla_max: 180
    - id: 4
      token: qiivTq9Z.TXYjOyZBLXGkjgN0Adxz2BAqnopkbvlE
      altura_min: 0.5
      altura_max: 3.5
      temperatura_min: -5
      temperatura_max: 25
      presion_min: 950
      presion_max: 1050
      bateria_max: 100
      bateria_min: 10
      interval_minutes_min: 0.3
      interval_minutes_max: 0.5
      probabilidad_falla: 0.008
      duracion_falla_min: 10
      duracion_falla_max: 30
    - id: 5
      token: EbUbysGX.v5XDynCpnp5fl1XOgVoF7yQLWoqNeWqD
      altura_min: 0.5
      altura_max: 3.5
      temperatura_min: -5
      temperatura_max: 25
      presion_min: 950
      presion_max: 1050
      bateria_max: 100
      bateria_min: 10
      probabilidad_falla: 0.012
      duracion_falla_min: 15
      duracion_falla_max: 60
    - id: 6
      token: 4uAz2hRn.KBYSf7evvrUoDwmyGa07bq8yaUQZXV72
      altura_min: 0.5
      altura_max: 3.5
      temperatura_min: -5
      temperatura_max: 25
      presion_min: 950
      presion_max: 1050
      bateria_max: 100
      bateria_min: 10
      probabilidad_falla: 0.006
      duracion_falla_min: 8
      duracion_falla_max: 25
    - id: 7
      token: ygXXkJWe.tQjJ3jAR32PAUcDKKsORgP2g8M9FGgf5
      altura_min: 0.5
      altura_max: 3.5
      temperatura_min: -5
      temperatura_max: 25
      presion_min: 950
      presion_max: 1050
      bateria_max: 100
      bateria_min: 10
      interval_minutes_min: 0.35
      interval_minutes_max: 0.6
      probabilidad_falla: 0.003
      duracion_falla_min: 20
      duracion_falla_max: 180
